//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AKUDDbContext : DbContext
    {
        public AKUDDbContext()
            : base("name=AKUDDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Koreograf> Koreografi { get; set; }
        public virtual DbSet<Sastav> Sastavi { get; set; }
        public virtual DbSet<Vodi> Vodjenje { get; set; }
        public virtual DbSet<Igrac> Igraci { get; set; }
        public virtual DbSet<Pripada> Pripadanje { get; set; }
        public virtual DbSet<Proba> Probe { get; set; }
        public virtual DbSet<Koncert> Koncerti { get; set; }
        public virtual DbSet<Nastupa> Nastupaju { get; set; }
        public virtual DbSet<Nosnja> Nosnje { get; set; }
        public virtual DbSet<Muzika> Muzike { get; set; }
    }
}
