//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nosnja
    {
        public int ID_NOS { get; set; }
        public int NastupaIgracID_IG { get; set; }
        public int NastupaKoncertID_KC { get; set; }
        public string IME_NOS { get; set; }
    
        public virtual Nastupa Nastupa { get; set; }
    }
}
