
CREATE PROCEDURE P_Projekat_PokusajIgraciImena
AS 
DECLARE PROJEKAT_CURSOR CURSOR 
FOR SELECT IME_IG FROM Igraci
DECLARE @i VARCHAR(30); 
BEGIN 
OPEN PROJEKAT_CURSOR;
WHILE @@FETCH_STATUS = 0 
BEGIN 
PRINT @i;
FETCH NEXT FROM PROJEKAT_CURSOR 
INTO @i;
END;
CLOSE PROJEKAT_CURSOR; 
DEALLOCATE PROJEKAT_CURSOR; 
END;